version: '3.8'

services:
  # Service de l'API FastAPI
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app/app
      - ./tasks:/app/tasks
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  # Service de la Base de Données PostgreSQL
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

  # Service Redis pour le Broker Celery
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

   # Service Worker Celery
  worker:
    build: .
    # ==========================================================
    # CORRECTION : Changer la commande pour utiliser le pool "solo"
    # ==========================================================
    command: celery -A tasks.celery_app worker --loglevel=info --pool=solo
    # ==========================================================
    volumes:
      - ./app:/app/app
      - ./tasks:/app/tasks
    env_file:
      - ./.env
    depends_on:
      - redis
      - db # Le worker a besoin de se connecter à la BDD

volumes:
  postgres_data: